name: Astronomy GraphQL API
values:
  - key: URL
    value: ''
    enabled: true
  - key: username
    value: ''
    enabled: true
  - key: password
    value: ''
    enabled: true
  - key: token
    value: ''
    enabled: true
  - key: query_spkid
    value: ''
    enabled: true
  - key: mutate_spkid
    value: ''
    enabled: true
  - key: page
    value: ''
    enabled: true
color: 180
