stages:
  - test

test_job:
  stage: test
  image: node:18
  script:
    - echo "CI working"
    - node --version
    - npm --version

postman_tests:
  stage: test
  image: node:18
  before_script: 
    - npm install -g newman newman-reporter-junitfull
  script:
    - npm install
    - npm run seed
    - newman run "./postman/astronomy_postman_collection.json" \
      --environment "./postman/astronomy_postman_environment.json" \
      --reporters cli,junit \
      --reporter-junit-export newman-report.xml
  artifacts:
    when: always
    paths: 
      - newman-report.xml
    reports:
      junit: newman-report.xml