stages:
  - lint
  - test

lint:
  stage: lint
  image: node:18
  script: 
    - npm ci
    - npm run lint

postman_tests:
  stage: test
  image: node:18
  before_script: 
    - npm ci
    - npm install -g newman newman-reporter-junitfull newman-reporter-htmlextra
  script:
    - npm run seed
    - npm start &
    - newman run "./postman/astronomy_postman_collection.json" --environment "./postman/astronomy_postman_environment.json" --reporters cli,junit,htmlextra --reporter-junit-export newman-report.xml --reporter-htmlextra-export newman-report.html
  artifacts:
    when: always
    paths: 
      - newman-report.xml
      - newman-report.html
    reports:
      junit: newman-report.xml