# $POSTMAN_COLLECTION_ID = 69ab5c5d99fcef7056ba1f58
# $POSTMAN_ENV_ID = 42893409-9f6fb192-78dd-4ddc-a8b4-8d848fd9a765
# $POSTMAN_API_KEY = PMAK-69affca233ea930001445d46-b5bedb2682f4493ef9c9f5f2790c2c98ef

stages:
  - test

test_job:
  stage: test
  script:
    - echo "CI working"

postman_tests:
  stage: test
  image: node:18
  before_script: 
    - npm install -g newman newman-reporter-junitfull
  script:
    - npm run seed
    - newman run "https://api.getpostman.com/collections/69ab5c5d99fcef7056ba1f58?apikey=PMAK-69affca233ea930001445d46-b5bedb2682f4493ef9c9f5f2790c2c98ef" \
      --environment "https://api.getpostman.com/environments/42893409-9f6fb192-78dd-4ddc-a8b4-8d848fd9a765?apikey=PMAK-69affca233ea930001445d46-b5bedb2682f4493ef9c9f5f2790c2c98ef" \
      --reporters cli,junit \
      --reporter-junit-export newman-report.xml
  artifacts:
    when: always
    paths: 
      - newman-report.xml
    reports:
      junit: newman-report.xml